DEFINES+=PROJECT_CONF_H=\"project-conf.h\"
CONTIKI_PROJECT = sensor-demoestesi

all: $(CONTIKI_PROJECT)

APPS += mqtt

TARGET=stm32nucleo-spirit1
SENSORBOARD=iks01a1

SMALL = 1

CONTIKI_WITH_IPV6 = 1

CONTIKI = /home/diego/Documentos/NuevoProyecto/contiki
include $(CONTIKI)/Makefile.include
